import os
import pandas as pd

os.makedirs('data/processed/crops', exist_ok=True)

crops_data = [
    {
        "crop_id": "CROP_001",
        "crop_name": "Paddy",
        "regional_name_hi": "धान",
        "regional_name_mr": "भात",
        "category": "GRAIN",
        "season": "Kharif",
        "state_region": "Maharashtra, Punjab, Uttar Pradesh, Goa",
        "procurement_eligibility": True,
        "msp_rs_per_quintal": 2320.00,
        "procurement_period": "October - March",
        "shelf_life_days": 365,
        "urgency_level": "LOW",
        "perishability_score": 0.15,
        "moisture_std_pct": 14.0
    },
    {
        "crop_id": "CROP_002",
        "crop_name": "Wheat",
        "regional_name_hi": "गेहूं",
        "regional_name_mr": "गहू",
        "category": "GRAIN",
        "season": "Rabi",
        "state_region": "Punjab, Uttar Pradesh, Madhya Pradesh, Maharashtra",
        "procurement_eligibility": True,
        "msp_rs_per_quintal": 2275.00,
        "procurement_period": "April - June",
        "shelf_life_days": 365,
        "urgency_level": "LOW",
        "perishability_score": 0.15,
        "moisture_std_pct": 12.0
    },
    {
        "crop_id": "CROP_003",
        "crop_name": "Cotton",
        "regional_name_hi": "कपास",
        "regional_name_mr": "कापूस",
        "category": "FIBER",
        "season": "Kharif",
        "state_region": "Maharashtra, Punjab, Gujarat, Madhya Pradesh",
        "procurement_eligibility": True,
        "msp_rs_per_quintal": 7521.00,
        "procurement_period": "October - February",
        "shelf_life_days": 300,
        "urgency_level": "LOW",
        "perishability_score": 0.20,
        "moisture_std_pct": 8.0
    },
    {
        "crop_id": "CROP_004",
        "crop_name": "Soybean",
        "regional_name_hi": "सोयाबीन",
        "regional_name_mr": "सोयाबीन",
        "category": "OILSEED",
        "season": "Kharif",
        "state_region": "Maharashtra, Madhya Pradesh",
        "procurement_eligibility": True,
        "msp_rs_per_quintal": 5320.00,
        "procurement_period": "October - January",
        "shelf_life_days": 180,
        "urgency_level": "MEDIUM",
        "perishability_score": 0.30,
        "moisture_std_pct": 12.0
    },
    {
        "crop_id": "CROP_005",
        "crop_name": "Maize",
        "regional_name_hi": "मक्का",
        "regional_name_mr": "मका",
        "category": "GRAIN",
        "season": "Kharif",
        "state_region": "Maharashtra, Karnataka, Madhya Pradesh, Uttar Pradesh",
        "procurement_eligibility": True,
        "msp_rs_per_quintal": 2225.00,
        "procurement_period": "October - December",
        "shelf_life_days": 240,
        "urgency_level": "LOW",
        "perishability_score": 0.25,
        "moisture_std_pct": 14.0
    },
    {
        "crop_id": "CROP_006",
        "crop_name": "Tur (Arhar)",
        "regional_name_hi": "तुअर / अरहर",
        "regional_name_mr": "तूर",
        "category": "PULSE",
        "season": "Kharif",
        "state_region": "Maharashtra, Madhya Pradesh, Karnataka",
        "procurement_eligibility": True,
        "msp_rs_per_quintal": 7550.00,
        "procurement_period": "December - March",
        "shelf_life_days": 300,
        "urgency_level": "LOW",
        "perishability_score": 0.20,
        "moisture_std_pct": 12.0
    },
    {
        "crop_id": "CROP_007",
        "crop_name": "Moong",
        "regional_name_hi": "मूंग",
        "regional_name_mr": "मूग",
        "category": "PULSE",
        "season": "Kharif",
        "state_region": "Maharashtra, Rajasthan, Madhya Pradesh",
        "procurement_eligibility": True,
        "msp_rs_per_quintal": 8682.00,
        "procurement_period": "September - November",
        "shelf_life_days": 270,
        "urgency_level": "LOW",
        "perishability_score": 0.20,
        "moisture_std_pct": 12.0
    },
    {
        "crop_id": "CROP_008",
        "crop_name": "Urad",
        "regional_name_hi": "उड़द",
        "regional_name_mr": "उडीद",
        "category": "PULSE",
        "season": "Kharif",
        "state_region": "Maharashtra, Madhya Pradesh, Uttar Pradesh",
        "procurement_eligibility": True,
        "msp_rs_per_quintal": 7400.00,
        "procurement_period": "October - December",
        "shelf_life_days": 270,
        "urgency_level": "LOW",
        "perishability_score": 0.20,
        "moisture_std_pct": 12.0
    },
    {
        "crop_id": "CROP_009",
        "crop_name": "Gram (Chana)",
        "regional_name_hi": "चना",
        "regional_name_mr": "हरभरा",
        "category": "PULSE",
        "season": "Rabi",
        "state_region": "Madhya Pradesh, Maharashtra, Rajasthan",
        "procurement_eligibility": True,
        "msp_rs_per_quintal": 5440.00,
        "procurement_period": "March - May",
        "shelf_life_days": 300,
        "urgency_level": "LOW",
        "perishability_score": 0.20,
        "moisture_std_pct": 12.0
    },
    {
        "crop_id": "CROP_010",
        "crop_name": "Mustard",
        "regional_name_hi": "सरसों",
        "regional_name_mr": "मोहरी",
        "category": "OILSEED",
        "season": "Rabi",
        "state_region": "Rajasthan, Madhya Pradesh, Uttar Pradesh",
        "procurement_eligibility": True,
        "msp_rs_per_quintal": 5650.00,
        "procurement_period": "February - April",
        "shelf_life_days": 240,
        "urgency_level": "LOW",
        "perishability_score": 0.25,
        "moisture_std_pct": 9.0
    },
    {
        "crop_id": "CROP_011",
        "crop_name": "Groundnut",
        "regional_name_hi": "मूंगफली",
        "regional_name_mr": "भुईमूग",
        "category": "OILSEED",
        "season": "Kharif",
        "state_region": "Gujarat, Maharashtra, Andhra Pradesh",
        "procurement_eligibility": True,
        "msp_rs_per_quintal": 6783.00,
        "procurement_period": "October - January",
        "shelf_life_days": 180,
        "urgency_level": "MEDIUM",
        "perishability_score": 0.30,
        "moisture_std_pct": 8.0
    },
    {
        "crop_id": "CROP_012",
        "crop_name": "Bajra",
        "regional_name_hi": "बाजरा",
        "regional_name_mr": "बाजरी",
        "category": "MILLET",
        "season": "Kharif",
        "state_region": "Rajasthan, Uttar Pradesh, Maharashtra",
        "procurement_eligibility": True,
        "msp_rs_per_quintal": 2625.00,
        "procurement_period": "October - December",
        "shelf_life_days": 180,
        "urgency_level": "LOW",
        "perishability_score": 0.20,
        "moisture_std_pct": 13.0
    },
    {
        "crop_id": "CROP_013",
        "crop_name": "Mango",
        "regional_name_hi": "आम",
        "regional_name_mr": "आंबा",
        "category": "HORTICULTURE",
        "season": "Summer/Zaid",
        "state_region": "Goa, Maharashtra, Uttar Pradesh",
        "procurement_eligibility": True,
        "msp_rs_per_quintal": 4800.00,
        "procurement_period": "March - June",
        "shelf_life_days": 14,
        "urgency_level": "HIGH",
        "perishability_score": 0.85,
        "moisture_std_pct": 80.0
    },
    {
        "crop_id": "CROP_014",
        "crop_name": "Sugarcane",
        "regional_name_hi": "गन्ना",
        "regional_name_mr": "ऊस",
        "category": "COMMERCIAL",
        "season": "Crushing",
        "state_region": "Maharashtra, Uttar Pradesh, Karnataka",
        "procurement_eligibility": True,
        "msp_rs_per_quintal": 340.00,
        "procurement_period": "October - April",
        "shelf_life_days": 3,
        "urgency_level": "CRITICAL",
        "perishability_score": 0.90,
        "moisture_std_pct": 20.0
    },
    {
        "crop_id": "CROP_015",
        "crop_name": "Banana",
        "regional_name_hi": "केला",
        "regional_name_mr": "केळी",
        "category": "HORTICULTURE",
        "season": "All-Season",
        "state_region": "Maharashtra, Tamil Nadu, Gujarat",
        "procurement_eligibility": True,
        "msp_rs_per_quintal": 2150.00,
        "procurement_period": "Year-round",
        "shelf_life_days": 7,
        "urgency_level": "HIGH",
        "perishability_score": 0.80,
        "moisture_std_pct": 75.0
    },
    {
        "crop_id": "CROP_016",
        "crop_name": "Tomato",
        "regional_name_hi": "टमाटर",
        "regional_name_mr": "टोमॅटो",
        "category": "PERISHABLE_VEGETABLE",
        "season": "Rabi/Zaid",
        "state_region": "Maharashtra, Andhra Pradesh, Karnataka",
        "procurement_eligibility": True,
        "msp_rs_per_quintal": 1650.00,
        "procurement_period": "November - March",
        "shelf_life_days": 5,
        "urgency_level": "CRITICAL",
        "perishability_score": 0.95,
        "moisture_std_pct": 90.0
    },
    {
        "crop_id": "CROP_017",
        "crop_name": "Onion",
        "regional_name_hi": "प्याज",
        "regional_name_mr": "कांदा",
        "category": "PERISHABLE_VEGETABLE",
        "season": "Rabi/Kharif",
        "state_region": "Maharashtra, Madhya Pradesh, Karnataka",
        "procurement_eligibility": True,
        "msp_rs_per_quintal": 1800.00,
        "procurement_period": "December - May",
        "shelf_life_days": 45,
        "urgency_level": "HIGH",
        "perishability_score": 0.50,
        "moisture_std_pct": 65.0
    },
    {
        "crop_id": "CROP_018",
        "crop_name": "Potato",
        "regional_name_hi": "आलू",
        "regional_name_mr": "बटाटा",
        "category": "PERISHABLE_VEGETABLE",
        "season": "Rabi",
        "state_region": "Uttar Pradesh, West Bengal, Bihar",
        "procurement_eligibility": True,
        "msp_rs_per_quintal": 1400.00,
        "procurement_period": "January - April",
        "shelf_life_days": 60,
        "urgency_level": "MEDIUM",
        "perishability_score": 0.40,
        "moisture_std_pct": 60.0
    }
]

df = pd.DataFrame(crops_data)
out_csv = 'data/processed/crops/crops_master.csv'
df.to_csv(out_csv, index=False)
print(f"Saved {len(df)} crops to {out_csv}")
